[language.python]
version = "3.11"
requirements = "backend/requirements.txt"

[phases.setup]
nixPkgs = ["git", "python311", "python311Packages.pip", "ffmpeg", "pkg-config"]

[phases.install]
cmds = []

[start]
cmd = "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
