[phases.setup]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/refs/tags/23.11.tar.gz"

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt"
]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
