[language.python]
version = "3.11"
requirements = "backend/requirements.txt"  # ✅ Correct path

[phases.setup]
nixPkgs = ["git", "python311", "python311Packages.pip", "ffmpeg", "pkg-config"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt"  # ✅ Match the correct location
]

[start]
cmd = "python3 -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
