[language.python]
version = "3.11"

[phases.setup]
nixPkgs = [
  "git",
  "ffmpeg",
  "pkg-config",
  "python311",
  "python311Packages.fastapi",
  "python311Packages.uvicorn",
  "python311Packages.requests",       # if needed
  "python311Packages.pydantic",       # required by FastAPI
  "python311Packages.numpy",          # optional: if you use numpy
]

[start]
cmd = "cd backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

