[language.python]
version = "3.11"

[phases.setup]
nixPkgs = [
  "git",
  "ffmpeg",
  "pkg-config",
  "python311",
  "python311Packages.uvicorn",
  "python311Packages.pydantic",
  "python311Packages.requests",
  "python311Packages.numpy",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel"
]

[phases.install]
cmds = []

[start]
cmd = "cd backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
